CREATE SCHEMA [ERRORLOG] AUTHORIZATION [dbo]
GO

CREATE TABLE ERRORLOG.SERVERS (
    ID INT IDENTITY(1,1),
    NAME VARCHAR(100),
    PATH VARCHAR(1024),
    LASTPROCESSTIME DATETIME
)
GO
CREATE TABLE ERRORLOG.LOGMASTER (
    ID INT IDENTITY (1,1),
    SERVERID INT,
    NAME VARCHAR(100), 
    MODIFIEDDATETIME DATETIME
)
GO
CREATE TABLE ERRORLOG.LOGS (
    ID INT IDENTITY (1,1),
    LOGID INT,
    LogDate	 DATETIME,
    ProcessInfo	VARCHAR(20),
    Text	 VARCHAR(500)
)
GO
